[www]
user = www-data
group = www-data
listen = 9000

; Permet aux variables d'environnement d'être accessibles en PHP
clear_env = no

; Logs
access.log = /var/log/php-fpm/access.log
slowlog = /var/log/php-fpm/slow.log
request_slowlog_timeout = 10s

; Performance
pm = dynamic
pm.max_children = 10
pm.start_servers = 3
pm.min_spare_servers = 2
pm.max_spare_servers = 5
pm.max_requests = 1000

; Health check
ping.path = /ping
ping.response_code = 200
